connection:
  swaggerAddresses:
#    ngenie-common-services: http://ingressinside.loadtest-tvh.mts-corp.ru/ngenie-common-services/desc/swagger.json
#    ngenie-security: http://ingressinside.loadtest-tvh.mts-corp.ru/ngenie-security/desc/swagger.json
#    ngenie-web-console: http://ingressinside.loadtest-tvh.mts-corp.ru/ngenie-web-console/desc/swagger.json
    tvh-billing: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-billing/desc/swagger.json
    tvh-billing-v2: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-billing-v2/swagger
#    tvh-cashback: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-cashback/desc/swagger.json
#    tvh-cm: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-cm/desc/swagger.json
#    tvh-cms: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-cms/desc/swagger.json
#    tvh-core: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-core/desc/swagger.json
#    tvh-error: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-error/desc/swagger.json
#    tvh-evp-publisher: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-evp-publisher/desc/swagger.json
#    tvh-foris-esb-adapter: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-foris-esb-adapter/desc/swagger.json
#    tvh-foris-marker: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-foris-marker/desc/swagger.json
#    tvh-in-app-purchase: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-in-app-purchase/desc/swagger.json
#    tvh-maintenance: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-maintenance/desc/swagger.json
#    tvh-master-hub-adapter: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-master-hub-adapter/desc/swagger.json
#    tvh-metaload: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-metaload/desc/swagger.json
#    tvh-migration: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-migration/desc/swagger.json
#    tvh-mts-money-adapter: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-mts-money-adapter/desc/swagger.json
#    tvh-notification: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-notification/desc/swagger.json
#    tvh-offers: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-offers/desc/swagger.json
#    tvh-ott-api-gateway: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-ott-api-gateway/desc/swagger.json
#    tvh-ott-order: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-ott-order/desc/swagger.json
#    tvh-products: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-products/desc/swagger.json
#    tvh-products-v2: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-products-v2/desc/swagger.json
#    tvh-promis: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-promis/desc/swagger.json
#    tvh-promis-admin: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-promis-admin/desc/swagger.json
#    tvh-provisioning: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-provisioning/desc/swagger.json
#    tvh-registration: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-registration/desc/swagger.json
#    tvh-reports: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-reports/desc/swagger.json
#    tvh-retailer-adapter: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-retailer-adapter/desc/swagger.json
#    tvh-security: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-security/desc/swagger.json
#    tvh-stb-api-gateway: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-stb-api-gateway/desc/swagger.json
#    tvh-stb-order: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-stb-order/desc/swagger.json
#    tvh-support: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-support/desc/swagger.json
#    tvh-test-tools: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-test-tools/desc/swagger.json
  scrapeInterval: 5000