connection:
  swaggerAddresses:
    ngenie-common-services: http://ingressinside.loadtest-tvh.mts-corp.ru/ngenie-common-services/swagger-ui
    ngenie-security: http://ingressinside.loadtest-tvh.mts-corp.ru/ngenie-security/swagger-ui
    ngenie-web-console: http://ingressinside.loadtest-tvh.mts-corp.ru/ngenie-web-console/swagger-ui
    tvh-billing: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-billing/swagger-ui
    tvh-billing-v2: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-billing-v2/swagger-ui
    tvh-cashback: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-cashback/swagger-ui
    tvh-cm: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-cm/swagger-ui
    tvh-cms: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-cms/swagger-ui
    tvh-core: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-core/swagger-ui
    tvh-error: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-error/swagger-ui
    tvh-evp-publisher: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-evp-publisher/swagger-ui
    tvh-foris-esb-adapter: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-foris-esb-adapter/swagger-ui
    tvh-foris-marker: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-foris-marker/swagger-ui
    tvh-in-app-purchase: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-in-app-purchase/swagger-ui
    tvh-maintenance: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-maintenance/swagger-ui
    tvh-master-hub-adapter: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-master-hub-adapter/swagger-ui
    tvh-metaload: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-metaload/swagger-ui
    tvh-migration: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-migration/swagger-ui
    tvh-mts-money-adapter: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-mts-money-adapter/swagger-ui
    tvh-notification: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-notification/swagger-ui
    tvh-offers: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-offers/swagger-ui
    tvh-ott-api-gateway: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-ott-api-gateway/swagger-ui
    tvh-ott-order: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-ott-order/swagger-ui
    tvh-products: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-products/swagger-ui
    tvh-products-v2: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-products-v2/swagger-ui
    tvh-promis: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-promis/swagger-ui
    tvh-promis-admin: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-promis-admin/swagger-ui
    tvh-provisioning: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-provisioning/swagger-ui
    tvh-registration: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-registration/swagger-ui
    tvh-reports: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-reports/swagger-ui
    tvh-retailer-adapter: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-retailer-adapter/swagger-ui
    tvh-security: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-security/swagger-ui
    tvh-stb-api-gateway: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-stb-api-gateway/swagger-ui
    tvh-stb-order: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-stb-order/swagger-ui
    tvh-support: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-support/swagger-ui
    tvh-test-tools: http://ingressinside.loadtest-tvh.mts-corp.ru/tvh-test-tools/swagger-ui
  scrapeInterval: 5000